# Generated by Django 3.1 on 2020-09-02 10:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('searchBar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordsearch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keywordsearch',
            name='spin',
            field=models.IntegerField(default=80, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='keywordsearch',
            name='status',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='keywordsearch',
            name='total_crawled_result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordsearch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='keywordsearch',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='keywordsearch',
            name='filter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('url_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('type_of_text', models.CharField(blank=True, max_length=10, null=True)),
                ('url_extension_type', models.CharField(blank=True, max_length=10, null=True)),
                ('matched_similarity', models.IntegerField(blank=True, null=True)),
                ('keywordId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='keywordId', to='searchBar.keywordsearch')),
            ],
            options={
                'verbose_name_plural': 'Search Result',
            },
        ),
        migrations.CreateModel(
            name='Keyword_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('keywordId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_Id', to='searchBar.keywordsearch')),
            ],
            options={
                'verbose_name_plural': 'Keyword category',
            },
        ),
        migrations.CreateModel(
            name='company_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_url', models.CharField(blank=True, max_length=255, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
                ('place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('matched_similarity', models.IntegerField(blank=True, null=True)),
                ('keywordId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='search_keyword_Id', to='searchBar.keywordsearch')),
                ('searchResultId', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='search_result_Id', to='searchBar.searchresult')),
            ],
            options={
                'verbose_name_plural': 'Company Info',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('parent', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='searchBar.category')),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
    ]
