from django.urls import path

from . import views

# Define url patterns for 'collector' app here.

app_name = 'api'
urlpatterns = [
    path('json_converter/', views.json_converter.as_view(),
         name="json_converter"),
    path('text_comparison/', views.text_to_converter.as_view(),
         name="text_comparison"),
    path('similarity_keyword/', views.similarity_keyword.as_view(),
         name="similarity_keyword"),
    path('Similarity_cosine/', views.Similarity_cosine.as_view(), name="Similarity_cosine"),
    path('Image_manuplator/', views.Image_manuplator.as_view(),
         name="Image_manuplator"),
    path('Image_change/', views.Image_change.as_view(),
         name="Image_change"),
    path('text_to_paraphrase/', views.text_to_paraphrase.as_view(),
         name="text_to_paraphrase"),
    path('text_classification/', views.text_classification.as_view(),
         name="text_classification"),
    path('clean_text/', views.clean_text.as_view(),
         name="clean_text"),
    path('document_classification/', views.document_classification.as_view(),
         name="document_classification"),
    path('website_scraping/', views.Website_scraping.as_view(),
         name="Website_scraping"),
    path('website_to_text/', views.website_to_text.as_view(),
         name="website_to_text"),
    


    # """Website To Text New Flow SOme Temp Api's"""
    path('website_to_text_no_clean/', views.website_to_text_no_clean.as_view(),
         name="website_to_text_no_clean"),
    path('website_to_text_p/', views.website_to_text_p.as_view(),
         name="website_to_text_p"),
    path('website_to_text_ul/', views.website_to_text_ul.as_view(),
         name="website_to_text_ul"),
    path('website_to_text_li/', views.website_to_text_li.as_view(),
         name="website_to_text_li"),
    path('delete_duplicatelink/', views.delete_duplicatelink.as_view(),
         name="delete_duplicatelink"),
    path('url_to_domain_name/', views.url_to_domain_name.as_view(),
         name="url_to_domain_name"),
    path('weburl_classification/', views.weburl_classification.as_view(),
         name="weburl_classification"),
    path('weburl_classification_no_autoclassification/', views.weburl_classification_no_autoclassification.as_view(),
         name="weburl_classification_no_autoclassification"),
    path('weburl_classification_list/', views.weburl_classification_list.as_view(),
         name="weburl_classification_list"),
    path('splittext_withoutspaces/', views.splittext_withoutspaces.as_view(),
         name="splittext_withoutspaces"),
    path('identify_companies_from_googlemaps/', views.identify_companies_from_googlemaps.as_view(),
         name="identify_companies_from_googlemaps"),
    path('google_maps/', views.google_maps.as_view(),
         name="google_maps"),
    path('find_words/', views.find_words.as_view(),
         name="find_words"),
    path('url_to_domain_suffix/', views.url_to_domain_suffix.as_view(),
         name="url_to_domain"),
    path('web_text_classification/', views.web_text_classification.as_view(),
         name="web_text_classification"),
    path('keyword_repetition/', views.keyword_repetition.as_view(),
         name="keyword_repetition"),
    path('cosine_similarity_with_keyword_repetition/', views.cosine_similarity_with_keyword_repetition.as_view(),
         name="cosine_similarity_with_keyword_repetition"),
    path('web_to_text_div_and_p/', views.web_to_text_div_and_p.as_view(),
         name="web_to_text_div_and_p"),
    path('rating/', views.rating.as_view(),
         name="rating"),
    path('classification/', views.classification.as_view(),
         name="classification"),
         
    # For Testing Pourpuse
    path('classification_no_auto/', views.classification_no_auto.as_view(),
         name="classification_no_auto"),
    # ----end----
    # Scraping Api with Node_js sc-scraper
    path('Bing_Website_scraper/', views.Bing_Website_scraper.as_view(),
         name="Bing_Website_scraper"),
    path('Google_Website_scraper/', views.Google_Website_scraper.as_view(),
         name="Google_Website_scraper"),
    path('Website_scraper/', views.Website_scraper.as_view(),
         name="Website_scraper"),
    path('Multi_search/', views.Multi_search.as_view(),
         name="Multi_search"),
    path('delete_duplicate_dict/', views.delete_duplicate_dict.as_view(),
         name="delete_duplicate_dict"),
    path('rating_percentage_list/', views.rating_percentage_list.as_view(),
         name="rating_percentage_list"),
    path('html_to_text/', views.html_to_text.as_view(),
         name="html_to_text"),
    path('text_classification_url_and_text/', views.text_classification_url_and_text.as_view(),
         name="text_classification_url_and_text"),
    path('url_to_text_extractor/', views.url_to_text_extractor.as_view(),
         name="url_to_text_extractor"),
    path('auto_search_keyword/', views.auto_search_keyword.as_view(),
         name="auto_search_keyword"),
    path('Mutli_search/', views.Mutli_search.as_view(),
         name="Mutli_search"),
    path('Similarity_sentence_match/', views.Similarity_sentence_match.as_view(),
         name="Similarity_sentence_match"),
    path('Similarity_word_match/', views.Similarity_word_match.as_view(),
         name="Similarity_word_match"),
    path('Purpose_module/', views.Purpose_module.as_view(),
         name="Purpose_module"),
    path('Purpose_details/', views.Purpose_details.as_view(),
         name="Purpose_details"),
    path('Rating_Purpose/', views.Rating_Purpose.as_view(),
         name="Rating_Purpose"),
         
    path('html_to_image/', views.html_to_image.as_view(),
         name="html_to_image"),
    path('SearchResults/', views.SearchResults.as_view(),
         name="SearchResults"),
    path('JsonSearch/',views.JsonSearch.as_view(),
         name="JsonSearch"),
#     path('googleAuth/',views.googleAuth.as_view(),
#         name='googleAuth'),
    path('Remove_links_table/',views.Remove_links_table.as_view(),
         name="Remove_links_table")
]
"""
NOTE: On Live must Be install this... Dependency 
apt-get install -y libsm6 libxext6 libxrender-dev
"""

